<a href="https://colab.research.google.com/github/Marcelo-Silvestre/Estudo_jogos/blob/main/Notebooks/jogos_estudo_15ABR26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
url_base = pd.read_excel("https://raw.githubusercontent.com/Marcelo-Silvestre/Estudo_jogos/main/bases/Lotof%C3%A1cil.xlsx")

In [3]:
df_jogos = pd.DataFrame(url_base)
df_jogos.head()

,Concurso,Data Sorteio,Bola1,Bola2,Bola3,Bola4,Bola5,Bola6,Bola7,Bola8,...,Rateio 13 acertos,Ganhadores 12 acertos,Rateio 12 acertos,Ganhadores 11 acertos,Rateio 11 acertos,Acumulado 15 acertos,Arrecadacao Total,Estimativa Prêmio,Acumulado sorteio especial Lotofácil da Independência,Observação
0,1,29/09/2003,2,3,5,6,9,10,11,13,...,"R$10,00",48807,"R$4,00",257593,"R$2,00","R$0,00","R$0,00","R$0,00","R$0,00",Estimativa de prêmio (15 ACERTOS) próximo conc...
1,2,06/10/2003,1,4,5,6,7,9,11,12,...,"R$10,00",81252,"R$4,00",478188,"R$2,00","R$0,00","R$0,00","R$0,00","R$0,00",ESTIMATIVA DE PRÊMIO PARA O PRÓXIMO CONCURSO (...
2,3,13/10/2003,1,4,6,7,8,9,10,11,...,"R$10,00",96244,"R$4,00",608211,"R$2,00","R$0,00","R$0,00","R$0,00","R$0,00",Estimativa de prêmio (15 ACERTOS) próximo conc...
3,4,20/10/2003,1,2,4,5,8,10,12,13,...,"R$10,00",123912,"R$4,00",706657,"R$2,00","R$0,00","R$0,00","R$0,00","R$0,00",Estimativa de prêmio (15 ACERTOS) próximo conc...
4,5,27/10/2003,1,2,4,8,9,11,12,13,...,"R$10,00",195636,"R$4,00",860992,"R$2,00","R$0,00","R$0,00","R$0,00","R$0,00",Estimativa de prêmio para o próximo concurso (...

In [24]:
df_resultados = df_jogos.iloc[:,2:17]
df_resultados

,Bola1,Bola2,Bola3,Bola4,Bola5,Bola6,Bola7,Bola8,Bola9,Bola10,Bola11,Bola12,Bola13,Bola14,Bola15
0,2,3,5,6,9,10,11,13,14,16,18,20,23,24,25
1,1,4,5,6,7,9,11,12,13,15,16,19,20,23,24
2,1,4,6,7,8,9,10,11,12,14,16,17,20,23,24
3,1,2,4,5,8,10,12,13,16,17,18,19,23,24,25
4,1,2,4,8,9,11,12,13,15,16,19,20,23,24,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3653,1,2,3,4,6,7,11,15,17,19,20,22,23,24,25
3654,1,2,4,5,6,10,11,12,17,18,19,21,22,23,24
3655,3,4,6,7,8,11,12,14,15,18,19,20,21,24,25
3656,1,2,4,7,8,10,12,13,17,18,19,20,22,23,24
3657,2,3,4,5,9,10,11,12,13,16,18,20,22,23,24

#2- Números sorteados, classificados em ordem crescente, na posição mais baixa (Bola 1)

In [18]:
df_bola1 = df_resultados['Bola1'].unique()
df_bola1.sort()
df_bola1

array([1, 2, 3, 4, 5, 6, 7, 9])

In [25]:
df_bola1_sort = df_resultados[df_resultados.iloc[:,0] == 1]
df_bola1_sort

,Bola1,Bola2,Bola3,Bola4,Bola5,Bola6,Bola7,Bola8,Bola9,Bola10,Bola11,Bola12,Bola13,Bola14,Bola15
1,1,4,5,6,7,9,11,12,13,15,16,19,20,23,24
2,1,4,6,7,8,9,10,11,12,14,16,17,20,23,24
3,1,2,4,5,8,10,12,13,16,17,18,19,23,24,25
4,1,2,4,8,9,11,12,13,15,16,19,20,23,24,25
5,1,2,4,5,6,7,10,12,15,16,17,19,21,23,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3647,1,2,5,7,8,9,10,11,13,14,15,18,19,20,22
3651,1,3,6,7,11,12,13,15,16,18,19,20,21,23,24
3653,1,2,3,4,6,7,11,15,17,19,20,22,23,24,25
3654,1,2,4,5,6,10,11,12,17,18,19,21,22,23,24
3656,1,2,4,7,8,10,12,13,17,18,19,20,22,23,24